#!/usr/bin/env php
<?php

declare(strict_types=1);
include __DIR__ . '/./classes/Autoloader.php';

$definedCmds = ['newConfig' => 'newconfig'];
$hasNewConfig = in_array($definedCmds['newConfig'], $argv) ?: false;

if ($hasNewConfig) {
    (new NewConfig($definedCmds['newConfig'], $argv))->run();
} else {
    // command-line arguments include --json
    $options = getopt('', array('symlink', 'json:'));
    $jsonPath = Utils::resolveArgumentValue('json', $options);
    $params = Utils::configVariablesImport($jsonPath);

    try {
        if (!$params) {
            throw new Exception("failed to import config file");
        }
    } catch (Exception $e){
        return 1;
    }

    (new Linker($params))->run();
}

return 0;