#!/usr/bin/env php
<?php

declare(strict_types=1);
include __DIR__ . '/./classes/Autoloader.php';

$definedCmds = ['newConfig' => 'newconfig'];
$hasNewConfig = in_array($definedCmds['newConfig'], $argv) ?: false;

if ($hasNewConfig) {
    (new NewConfig($definedCmds['newConfig'], $argv))->run();
} else {
    // command-line arguments include --json
    $options = getopt('', array('symlink', 'json:'));
    $jsonPath = Utils::resolveArgumentValue('json', $options);
    $isSymbolic = array_key_exists("symlink", $options);

    try {
        if (!$jsonPath) {
            throw new Exception("Illegal argument values");
        }
    } catch (Exception $e) {
        return 1;
    }

    $params = Utils::configVariablesImport($jsonPath);

    try {
        if (!$params) {
            throw new Exception("failed to import config file");
        }
    } catch (Exception $e) {
        return 1;
    }
    (new Linker($params))->run($isSymbolic);
}

return 0;
